# Generated by Django 4.1.7 on 2023-02-16 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=60, verbose_name='название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='название')),
                ('pages', models.PositiveSmallIntegerField(verbose_name='количество страниц')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='цена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comics', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('genres', models.ManyToManyField(related_name='comics', to='marvel.genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'комикс',
                'verbose_name_plural': 'комиксы',
                'ordering': ('pages',),
            },
        ),
    ]
